"""
NyayaSetu — Run the application.

USAGE:
    python main.py

This starts the FastAPI server at http://localhost:8000
  - API docs at http://localhost:8000/docs (auto-generated by FastAPI)
  - Frontend UI at http://localhost:8000/
  - Health check at http://localhost:8000/api/health

The reload=True flag watches your files for changes and automatically
restarts the server during development. Remove it for production.
"""

import uvicorn

if __name__ == "__main__":
    uvicorn.run(
        "api.main:app",       # Points to the `app` object in api/main.py
        host="0.0.0.0",       # Listen on all network interfaces
        port=8000,            # Port number
        reload=True,          # Auto-restart on file changes (dev only)
    )
